[package]
name = "bevy_devtools"
version = "0.1.0"
edition = "2018"

[features]
default = []
rapier = []
rapier3d = ["bevy_rapier3d", "bevy-inspector-egui/bevy_rapier3d", "rapier"]
rapier2d = ["bevy_rapier2d", "bevy-inspector-egui/bevy_rapier2d", "rapier"]


[dependencies]
bevy = { version = "0.5.0", default-features = false }
bevy-inspector-egui = { version = "0.5.1", default-features = false }
bevy_rapier3d = { version = "0.10", optional = true }
bevy_rapier2d = { version = "0.10", optional = true }

[dev-dependencies]
bevy = "0.5.0"
